### PR TITLE
Add rzil emulateme test bin

### PR DESCRIPTION
**Pull request by Heersin**
source file `float_ex1.c`
```C
#include <stdio.h>

int main(int argc, char **argv) {
        float a, b;
        a = 5.4;
        b = 0.000008;
        double c = a - b + a * b;
        printf("a = %f b = %f c = %e\n", a, b, c);
        return 0;
}

```

compiled by `arm-linux-gnueabihf-gcc --static -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3 float_ex1.c -o float_ex1_32`

### CODE REVIEW

**Comment by wargio** [comment]
push the sourcecode with the bin. just name it in the same way + `.c`

**Comment by XVilka** [comment]
Please add that compilation info in the commit message body so that it saved in the repository

**Comment by wargio** [comment]
better as a comment in the source file.

**Comment by XVilka** [comment]
There is more complicated `float_ex1.c` in the repo already. I suggest naming it `float_ex2.c`:
- https://github.com/rizinorg/rizin-testbins/blob/master/elf/float_ex1/

**Review by XVilka — APPROVED** [review]

**Pull request merged**
