### PR TITLE
Add symbolic link to test case-insensitivity of rizinorg/rizin#2236

### PR DESCRIPTION
**Pull request by kazarmy**
This pr adds a symbolic link to `2+5.bf` named `2＋5.BF` to test the case-insensitivity of rizinorg/rizin#2236.

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Will the symlink work on windows?

**Comment by kazarmy** [comment]
NTFS does support symbolic links ([Symbolic Links](https://docs.microsoft.com/en-us/windows/win32/fileio/symbolic-links#supported-operating-systems), [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)) and I've used them and they appear to work just like Linux symbolic links, so I think the answer is yes with contemporary Windows.

**Comment by kazarmy** [comment]
I'll remove this if the CI breaks

**Comment by thestr4ng3r** [comment]
Sounds good!

**Comment by kazarmy** [comment]
Oh no, creating symlinks on Windows requires Administrator rights (!)

**Pull request merged**
